### PR TITLE
Fix travis.yml to run tests & coverage after Documentation changes

### PR DESCRIPTION
**Pull request by NHDaly**
I think we broke travis a bit during the manual commits to master between #173 and  #176:
https://github.com/JunoLab/Blink.jl/compare/279797f..d428434

Looking at the latest builds, it doesn't seem to actually be running the tests! 😱
Also, we accidentally deleted the `after_success` `Coverage` section, so i've added that back. I'm still not sure what caused the Tests to stop running, but i'm looking into it!

### CODE REVIEW

**Comment by NHDaly** [comment]
Okay i think i've found it. So the problem was that you can't have both a `jobs:` section and a `matrix:` section, since apparently they're aliases for the same thing.

I've just moved the Documentation "stage" up into the main `matrix:include'.

**Comment by NHDaly** [comment]
Oh, huh, also, looking at the `.travis.yml` config, i guess you have to run julia as `xvfb-run julia` on linux in order for Blink to work?

It seems like when you try to open a `Blink` window through the regular `julia` command, you get an error:
```
│    LoadError: IOError: connect: connection refused (ECONNREFUSED)
```

@pfitzseb Do you know if I'm understanding that right? If so, we should /definitely/ add that instruction to the readme!

**Comment by pfitzseb** [comment]
Yeah we need `xvfb` to start Electron (see [here](https://electronjs.org/docs/tutorial/testing-on-headless-ci#configuring-the-virtual-display-server)). Adding this to the readme seems like a solid plan :)

**Comment by NHDaly** [comment]
Oh, wait, is it only on headless CI servers (it makes sense that you'd need that there because there's no local display).

My friend said he ran into the same error just running on his laptop.

I'm trying to write the change to the README now: is it that you _always_ need to launch julia via `xvfb-run julia` on Linux? Or should that only matter for CI systems?

**Comment by pfitzseb** [comment]
You need some kind of display server (which usually runs on Linux if you want to visualize stuff) -- headless system emulate one with `xvfb`. Blink/Electron works just fine on "normal" Linux systems without `xvfb` though.

**Pull request merged**
