### PR TITLE
Add documentation for the @js functions and friends

### PR DESCRIPTION
**Pull request by NHDaly**
Part of #160.

### CODE REVIEW

**Comment by NHDaly** [comment]
I would actually really appreciate someone's review on this one before I merge it! :)

Thanks!

**Comment by pfitzseb** [comment]
I feel like "...converted to javascript..." warrants some more explanation, but I'm not sure if those docstrings are the best place for that. LGTM otherwise.

**Comment by NHDaly** [comment]
Hmm agreed. Would it be too much to add something like this small paragraph to both of those?:

```
`expr` will be parsed as julia code, and then converted directly to the
equivalent javascript. Language keywords that don't exist in julia can be
represented with their macro equivalents, `@var`, `@new`, etc.
```

**Comment by NHDaly** [comment]
Okay cool! :) I've just added that, and i'll merge it now. We can always change the docstring later! :)

**Pull request merged**
