### PR TITLE
Julia v0.7 support

### LINKED ISSUE #132: Move to Julia 0.7

### LINKED ISSUE #145: Blink not building on Julia 1.0
`Blink.jl` is not building in `Julia 1.0`. The reason is due to previously deprecated functions and statement that are not more supported in `Julia 1.0`. The affected files are: `deps\build.jl`, `src\AtomShell\install.jl`, `src\AtomShell\process.jl`, `src\AtomShell\window.jl`. The functions `is_apple()`, `is_windows()`, `is_unix()`, `is_linux()` need to be substituted with `Sys.isapple()`, `Sys.iswindows()`, `Sys.isunix()`, `Sys.islinux()`respectively. The declaration `const` needs to be deleted.

### PR DESCRIPTION
**Pull request by rdeits**
Includes #139 plus a few more deprecation fixes. Also now checks out WebIO.jl master on 0.7+

Fixes #132 
Fixes #145

### CODE REVIEW

**Comment by piever** [comment]
I'm trying to make Interact functional again and am looking for an environment where things are supposed to work (among Blink, Mux, jupyter notebook). Is this PR + Blink the best bet?

**Comment by rdeits** [comment]
Yup, I have the tests passing locally for Blink with WebIO master and this PR. You'll also need https://github.com/JuliaGizmos/JSExpr.jl/pull/16 on Julia 1.0

**Comment by piever** [comment]
Cool, on my machine I have the first Interact slider on Julia 1.0! Thank you so much for all the amazing updating work!

**Comment by rdeits** [comment]
Hm, something is going very wrong with the Travis configuration. Even on v0.6 it's getting "connection refused" errors when trying to talk to electron.

**Comment by pfitzseb** [comment]
On appveyor (Julia 0.6) we're getting
```
ERROR (unhandled task failure): UndefVarError: serve not defined
Stacktrace:
 [1] (::Blink.##22#23)() at .\task.jl:335
```

Is this PR supposed to work on 0.6 at all? Imho we don't need to keep compatibility.

**Comment by rdeits** [comment]
I would be thrilled to just drop v0.6 entirely, yeah.

**Comment by piever** [comment]
I'm also in favor of dropping 0.6 support here

**Comment by rdeits** [comment]
done

**Comment by rdeits** [comment]
The "connection refused" error is still happening on Traivs. I don't know what could be causing that and I'm not sure how to debug it.

**Comment by piever** [comment]
I've had issues with Blink on Travis occasionally failing. Tbh, if this passes locally and has 0.7 lower bound, it may be worth merging anyway.

**Comment by rdeits** [comment]
I wonder if we're just getting a bad random port?

**Comment by rdeits** [comment]
`config.jl` currently picks a random port during module initialization, and that port is what Blink ends up using. If that port happened to be blocked by something else, then I wouldn't be surprised to see the connection problems.

**Comment by rdeits** [comment]
Ok, it seems like there's nothing wrong with the port, but for some reason the electron shell is just refusing the connection?

**Comment by rdeits** [comment]
I've pinged the Travis CI people about getting debug access to figure this out

**Comment by pfitzseb** [comment]
Btw, the last commits tests don't pass locally for me -- I get no output after `listening on:   2284`.

**Comment by rdeits** [comment]
Sorry, yeah, I've hacked it all up to try to debug the Travis issues. Should be back to normal shortly

**Comment by rdeits** [comment]
Ok, I'm a moron :-p. My changes to `.travis.yml` had resulted in the `TESTCMD` variable being ignored, so we weren't running with `xvdb-run`. That caused electron to just silently fail. Should be all fixed momentarily.

**Comment by rdeits** [comment]
Ok, we're in business! Tests are passing with Julia v0.7. They're still failing on 1.0, but only because we're waiting for https://github.com/JuliaGizmos/JSExpr.jl/pull/16

**Comment by sglyon** [comment]
Thank you @rdeits for all the hard work on getting this and related packages working! We owe you

**Comment by piever** [comment]
Now that WebIO and JSExpr PRs have been merged, I guess this one can also be merged and we can tag Blink 0.8.0 ?

**Comment by rdeits** [comment]
I'll update this PR to check out WebIO and JSExpr master, just to make sure everything is actually working first.

**Comment by rdeits** [comment]
Huh, appveyor is consistently failing when trying to uninstall AtomShell: 

```
ERROR: LoadError: IOError: unlink: operation not permitted (EPERM)
Stacktrace:
 [1] uv_error at .\libuv.jl:85 [inlined]
 [2] unlink(::String) at .\file.jl:743
 [3] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:253
 [4] #rm at .\none:0 [inlined]
 [5] #rm#9(::Bool, ::Bool, ::Function, ::String) at .\file.jl:263
 [6] #rm at .\none:0 [inlined]
 [7] rm′ at C:\projects\blink-jl\src\AtomShell\install.jl:3 [inlined]
 [8] uninstall() at C:\projects\blink-jl\src\AtomShell\install.jl:12
```

**Comment by rdeits** [comment]
Are we perhaps trying to delete a folder instead of a file now? https://stackoverflow.com/a/10979105

**Comment by pfitzseb** [comment]
We are, but `rm′` handles that just fine. I suspect there's still an electron process running when we try to delete the dir. Will look into it.

**Comment by pfitzseb** [comment]
Ok, so the issue is that `Window()` creates three electron subprocesses, of which only one is closed by `destroy(::Window)` (which isn't that surprising). Force closing the others via `quit(window.shell)` throws an error in JSON.jl, while killing them with `kill(window.shell.proc)` throws an error somewhere in HTTP.jl

Imho we need a way to gracefully close a `Shell` and should do that after the tests run, which will fix the test issue on Windows as well.

**Comment by piever** [comment]
Unrelated: we can stop checking out master of WebIO and JSExpr as they now have releases that support Julia 0.7

**Comment by pfitzseb** [comment]
Oh, and one slightly annoying thing is that HTTP.jl's info messages are printed when creating a new `Window`:
```
julia> w = Window()
Window(1, Electron(Process(`'C:\Users\Basti\.julia\dev\Blink\deps\atom\electron.exe' 'C:\Users\Basti\.julia\dev\Blink\src\AtomShell\main.js' port 5403`, ProcessRunning), Sockets.TCPSocket(Base.Libc.WindowsRawSocket(0x00000000000007f0) active, 0 bytes waiting), Dict{String,Any}("callback"=>##1#2())), Page(3, #undef, Dict{String,Any}("callback"=>##1#2()), Distributed.Future(1, 1, 3, nothing)))

julia> [ Info: Accept:  �    0↑     0↓    0s 127.0.0.1:4714:4714 ≣16
[ Info: Accept:  �    0↑     0↓    0s 127.0.0.1:4714:4714 ≣16
[ Info: Accept:  �    0↑     0↓    0s 127.0.0.1:4714:4714 ≣16
[ Info: Accept:  �    0↑     0↓    0s 127.0.0.1:4714:4714 ≣16
[ Info: Accept:  �    0↑     0↓    0s 127.0.0.1:4714:4714 ≣16
[ Info: Closed:  �    1↑     1↓�   4s 127.0.0.1:4714:4714 ≣16
```

Is there some way to suppress that?

**Comment by rdeits** [comment]
Can we wrap the `serve()` call in `Logging.with_logger()` and pass the logs to a `NullLogger` ?

**Comment by rdeits** [comment]
Another suggestion from Slack: https://github.com/JuliaLang/julia/pull/28229#issuecomment-410229612

**Comment by rdeits** [comment]
I implemented the suggestion from the comment linked above, and it seems to work fine.

**Comment by rdeits** [comment]
@pfitzseb I don't think the windows uninstall issue is severe enough to block getting an otherwise-working 0.7 version out. Do you agree?

**Comment by pfitzseb** [comment]
> I implemented the suggestion from JuliaLang/julia#28229 (comment) , and it seems to work fine.

That won't work in Juno or IJulia or in any environment that sets up their own logger. I'd be in favour of setting up a `BlinkLogger` that discards all `Info` level (and lower) logs from inside HTTP.jl and pipes everything else through to the former `current_logger()`. Basically something like [this](https://github.com/JunoLab/Atom.jl/blob/master/src/progress.jl).

> @pfitzseb I don't think the windows uninstall issue is severe enough to block getting an otherwise-working 0.7 version out. Do you agree?

Yeah, I agree. There still is the problem of creating zombie processes (at least on Windows, I didn't check on other OSs yet) that can't be closed without getting an error on the Julia side though. 

That doesn't have to hold up this PR. so merge at your leisure. Thanks again for the great work :)

**Comment by piever** [comment]
Merging this and tagging a new release, even if it's not perfect, is very helpful to update the rest of the stack (I need Blink to get Knockout to pass tests on 0.7 and 1.0).

**Comment by pfitzseb** [comment]
Alright, [done](https://github.com/JuliaLang/METADATA.jl/pull/17137).

(Wanted to let @rdeits do the honours of merging, but I guess getting a release out quickly *is* a good idea)

**Comment by NHDaly** [comment]
This was a stellar effort! Thank you all! I'm sorry i didn't help more in the process. Great job and thanks! :)

**Pull request merged**
