### PR TITLE
Added very very basic test

### PR DESCRIPTION
**Pull request by spencerlyon2**
Related to #25

### CODE REVIEW

**Comment by one-more-minute** [comment]
Good stuff. Do you know if Electron will run on Travis?

**Comment by spencerlyon2** [comment]
Hmm, I don't think it will. I just tried in a docker image (as I think that shell, only VM is pretty close to travis) and it didn't work. 

Oh well... Do you have any other ideas for how to get around that?

**Comment by EricForgy** [comment]
Hi @spencerlyon2 

What was the error? It didn't like to popup a window? I wonder if setting an option 

~~~javascript
show: false
~~~

i.e.

~~~julia
julia> w = Window(Blink.@d(:show => false))
~~~

would work? See http://electron.atom.io/docs/v0.27.0/api/browser-window/

**Comment by EricForgy** [comment]
Hi @spencerlyon2 and @one-more-minute 

I notice in your test you have a "sleep(5.0)". If my PR #35 is merged, you will no longer need this :)

**Comment by spencerlyon2** [comment]
@EricForgy I'm not sure what doesn't work here.

I'll give the `:show => false` idea a try -- good idea.

**Comment by spencerlyon2** [comment]
Didn't work:

```
julia> w = Window(Blink.@d(:show => false));
ERROR: connect: connection refused (ECONNREFUSED)
 in yieldto at ./task.jl:71
 in wait at ./task.jl:371
 in wait at ./task.jl:286
 in stream_wait at ./stream.jl:60
 in wait_connected at ./stream.jl:331
 in connect at socket.jl:669
 in try_connect at /root/.julia/v0.4/Blink/src/AtomShell/process.jl:49
 in init at /root/.julia/v0.4/Blink/src/AtomShell/process.jl:62
 in shell at /root/.julia/v0.4/Blink/src/AtomShell/process.jl:102
 in call at /root/.julia/v0.4/Blink/src/AtomShell/window.jl:37
```

This might be some strange thing running in a docker vm though, not sure. If I find some time I'll try to debug

**Comment by EricForgy** [comment]
The error message is actually encouraging :)

I've never done anything with Travis. How difficult would it be to just try it instead of debugging Docker? :)

**Comment by spencerlyon2** [comment]
I've updated the PR, but I need @one-more-minute to flip travis on for this repo

**Comment by EricForgy** [comment]
I can also give a try here I guess: https://travis-ci.org/EricForgy/Blink.jl ?

**Comment by EricForgy** [comment]
@spencerlyon2 , ohhh. This is my first foray into Travis. I see the linux tests failed, but OSX passed. That is a good sign :) I am trying something new now.

**Comment by EricForgy** [comment]
Hi @spencerlyon2 ,

It is interesting that the OSX tests are passing and not Linux. I just checked and the OSX tests still pass even without "show = false:, so that is not the problem.

I'm installing VirtualBox so I can have Julia on Linux, but I am no expert so do not have high expectations :)

**Comment by EricForgy** [comment]
@spencerlyon2 @one-more-minute ,

Would it make sense to turn on tests only for OSX for now since those tests are passing and figure out what is wrong on linux later? At least we'd have some test working and we can start adding to it.

**Comment by spencerlyon2** [comment]
My goal with the tests was to make sure that blink loaded and an electron window could be opened on all platforms. 

I think that because we don't have any other tests (yet), we shouldn't merge until we figure out how to run tests on Windows and Linux. 

Any other thoughts?

**Comment by EricForgy** [comment]
That makes sense, but I think Blink may not even work on Linux at the moment. Has anyone been able to get Blink to work on Linux? I'm on Windows, so I know it works on Windows and OSX (from Travis), but the very basic test fails on Linux and @tbreloff could not open a Window in #22 and he was on Linux.

It'd be great to start building some tests, even if just for OSX and Windows until someone comes along and gets things working on Linux.

**Comment by spencerlyon2** [comment]
I do have people using Blink on Ubuntu without problems. Not sure about other distros.

My vote would be to merge this under one of two conditions:

1. We get all 3 platforms to pass the test
2. We have other tests we want CI to track for platforms that currently do work

**Comment by tkelman** [comment]
Try with `xvfb-run` on Linux.

**Comment by spencerlyon2** [comment]
what do you mean? Try running what with that command?

**Comment by spencerlyon2** [comment]
@tkelman could this potentially help: http://rhysd.hatenablog.com/entry/2015/08/07/181418

Maybe it is what you had in mind. I can try to give it a shot later

**Comment by tkelman** [comment]
Before the `julia -e`. Ref http://elementalselenium.com/tips/38-headless and https://github.com/JuliaLang/Gtk.jl/blob/81a671358a45edc26cadbf3fe332f1a34cb5d33c/.travis.yml#L17

**Comment by EricForgy** [comment]
Drum roll :)

image

**Comment by EricForgy** [comment]
It worked! My tests are passing for linux! :)

But realized I was using the old yml. Will try again with Spencer's updated one...

**Comment by tkelman** [comment]
I'm not sure if `xvfb-run` is going to work for mac, might need to set an env var `TESTCMD: "xvfb-run julia"` for linux and `TESTCMD: "julia"` for osx or something like that

**Comment by EricForgy** [comment]
Yeah. My tests broke :)

May give that a try, but learning Travis is not high on my priority list at the moment. I may need to wait for you guys, but thank's for the suggestion :+1: :)

**Comment by tkelman** [comment]
Something like
```yml
matrix:
  include:
    - os: linux
      env: TESTCMD="xvfb-run julia"
    - os: osx
      env: TESTCMD="julia"
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("Blink"); Pkg.test("Blink"; coverage=true)'
```

**Comment by EricForgy** [comment]
Cool. Will try :muscle:

**Comment by EricForgy** [comment]
I tried:

~~~julia
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
env:
  - TESTCMD: "xvfb-run julia"
  - TESTCMD: "julia"
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("Plotly"); Pkg.test("Plotly"; coverage=true)'
~~~

**Comment by EricForgy** [comment]
Here's my latest yml:

~~~yml
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
matrix:
  include:
    - os: linux
      env: TESTCMD="xvfb-run julia"
    - os: osx
      env: TESTCMD="julia"
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("Blink"); Pkg.test("Blink"; coverage=true)'
~~~

Still not passing.

**Comment by tkelman** [comment]
Ahk, the travis matrix stuff is finicky - you either need to put everything in the matrix, or nothing. I'll open a PR against this branch.

**Comment by EricForgy** [comment]
Yay! That is awesome @tkelman :muscle:

With your yml, we have tests, including opening a Window, passing on both OSX and Linux :tada:

image

This is 2/3 of Spencer's 1st condition before merging :)

Next is Windows tests...

**Comment by tkelman** [comment]
> Next is Windows tests...

https://github.com/JuliaLang/Example.jl/blob/master/appveyor.yml

**Comment by EricForgy** [comment]
Ok. I added the example to my fork and changed "Example" -> "Blink" and signed up at Appveyor. Finger's crossed :)

**Comment by EricForgy** [comment]
Something wrong when building GnuTLS

https://ci.appveyor.com/project/EricForgy/blink-jl/build/1.0.4/job/h7d80lip6p4f1x4q

**Comment by tkelman** [comment]
Blink doesn't support 0.3 any more so you can remove the two JULIAVERSION lines for 0.3. The 0.4 versions of JuliaWeb packages should all be on MbedTLS rather than GnuTLS.

**Comment by EricForgy** [comment]
:+1: Trying again. Thanks

**Comment by EricForgy** [comment]
So far so good:

image

**Comment by spencerlyon2** [comment]
@one-more-minute, can you flip on Travis and appveyor for this repo? I think someone with admin privileges has to do it. 

Then I think we are good to go here, is that right @ericforgy?

**Comment by EricForgy** [comment]
As far as I can tell, yes :)

image

**Comment by one-more-minute** [comment]
CI enabled – Nice work everybody!

**Comment by tkelman** [comment]
AppVeyor failed? Would be good to add status badges.

**Comment by spencerlyon2** [comment]
Agreed that we should have badges. I don't know where to find the AppVeyor results, do you have a link?

**Comment by tkelman** [comment]
http://www.appveyor.com/docs/status-badges
see "for projects with public repositories"

**Comment by spencerlyon2** [comment]
Oh sorry, I meant I can't even find this repo on appveyor.

I looked here: https://ci.appveyor.com/project/JunoLab/blink-jl

but didn't find anything

**Comment by tkelman** [comment]
They don't really have org accounta last I checked, it'll be under whatever name @one-more-minute registered under. The badge can reference the github path though.

**Pull request merged**
