### PR TITLE
stop extending nonexistent Base.quit

### LINKED ISSUE #142: What to do about quit(::ElectronShell)?
Blink has:

https://github.com/JunoLab/Blink.jl/blob/3eff4999627968c979a7526de7cc218aa39e6755/src/AtomShell/process.jl#L107

where `quit` is imported from `Base`. `quit` is deprecated in 0.7 (now `exit`). Arguably, `Base.quit` shouldn't have been extended in the first place, so I don't think it should be replaced with an overload of `Base.exit` now. Should `AtomShell.quit` just not be exported?

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes #142.

### CODE REVIEW

**Comment by NHDaly** [comment]
Reopened PR to restart tests (i think there was a travis issue?)

**Comment by NHDaly** [comment]
Huh.. the test failure is consistent. 

It seems to be a deadlock or infinite loop?

**Comment by pfitzseb** [comment]
I'm getting 
image
locally when testing Blink. Not sure what's going on there.

**Comment by travigd** [comment]
CI for this should be re-run after #193.

**Comment by comaldave** [comment]
I am still seeing this error.
```
  Building Blink → `~/.juliapro/JuliaPro_v1.1.1.1/packages/Blink/1QOOi/deps/build.log`

julia> using Blink
[ Info: Precompiling Blink [ad839575-38b3-5650-b840-f874b8c74a25]
WARNING: could not import Base.quit into AtomShell
```
Seems safe to ignore.  I would like to help remove the error message.  I have been using Julia for 2 hours, very nice.

**Comment by NHDaly** [comment]
Thanks for the error report! 😁 Welcome to julia; I'm glad you're having a nice experience so far!

Yeah, this was fixed by this PR on the `master` branch of this repository, but that change hasn't been _released_ yet, so you're still seeing an older version. We're working on releasing it right now! (the release process has changed since our last release, so it's taking a bit longer than usual.)

Thanks for filing an error report. I hope you keep enjoying using Julia! :)

**Comment by haydenfree** [comment]
@NHDaly Is there any update on when the new release will be tagged? Thanks so much!

**Pull request merged**
