### PR TITLE
Fix tests for 0.7

### PR DESCRIPTION
**Pull request by vdayanand**
Working on this 
```
[ Info: Listening on: Sockets.InetAddr{IPv4}(ip"127.0.0.1", 0x1f90)
Error During Test at /Users/vdayanan/.julia/dev/Blink/test/runtests.jl:14
  Test threw exception MethodError(isapprox, (Dict{String,Any}(), 2.302585092994046), 0x0000000000006bdb)
  Expression: #= /Users/vdayanan/.julia/dev/Blink/test/runtests.jl:14 =# @js(w, Math.log(10)) ≈ log(10)
  MethodError: no method matching isapprox(::Dict{String,Any}, ::Float64)
  Closest candidates are:
    isapprox(!Matched::Number, ::Number; atol, rtol, nans) at floatfuncs.jl:259
  Stacktrace:
   [1] eval_test(::Expr, ::Expr, ::LineNumberNode) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:226
   [2] top-level scope at none:0
   [3] include at ./boot.jl:317 [inlined]
   [4] include_relative(::Module, ::String) at ./loading.jl:1034
   [5] include(::Module, ::String) at ./sysimg.jl:29
   [6] include(::String) at ./client.jl:393
   [7] top-level scope at none:0
   [8] eval(::Module, ::Any) at ./boot.jl:319
   [9] exec_options(::Base.JLOptions) at ./logging.jl:305
   [10] _start() at ./client.jl:427
ERROR: LoadError: There was an error during testing
in expression starting at /Users/vdayanan/.julia/dev/Blink/test/runtests.jl:14
ERROR: Package Blink errored during testing
```

### CODE REVIEW

**Comment by pfitzseb** [comment]
Hey, what's the status on this, @vdayanand?

**Comment by rdeits** [comment]
With WebSockets.jl master, HTTP.jl master, Mux with https://github.com/JuliaWeb/Mux.jl/pull/66 , WebIO with https://github.com/JuliaGizmos/WebIO.jl/pull/169 and Blink with this PR, I get all of the WebIO tests and Blink tests passing. I think we're in good shape if we can get everything merged and tagged.

**Comment by randyzwitch** [comment]
Getting all this worked out would be super helpful to me, as I rely on Blink.jl for ECharts.jl.

**Comment by pfitzseb** [comment]
Superceded by https://github.com/JunoLab/Blink.jl/pull/143.

**Pull request closed without merging**
