### PR TITLE
Fixed deprecation warning in size(win, w, h).

### PR DESCRIPTION
**Pull request by NHDaly**
Fixed:
```
  WARNING: `invoke(f, (types...), ...)` is deprecated, use `invoke(f, Tuple{types...}, ...)` instead
```
Also added "size tests" & reorganized `tests/` dir to match `src/` layout.

### CODE REVIEW

**Comment by NHDaly** [comment]
Oops, sorry, I fixed the build error. This should be good to review now! :)

**Comment by pfitzseb** [comment]
Looks good. The test error when running with `xvfb-run julia` might happen because the virtual screen isn't large enough or something? Maybe try creating the window with a smaller initial size.

**Comment by pfitzseb** [comment]
Yeah, looks good. Thanks for reminding me about this :)

**Comment by NHDaly** [comment]
:) thanks!

**Pull request merged**
