### PR TITLE
RFC: Allow user code to insert a middleware

### PR DESCRIPTION
**Pull request by shashi**
If files imported through `load!` or `import*!` methods include other files with relative paths, it will just work with this PR.

There's some security risk to allowing this in a web-facing Blink server, because it allows anyone to download the package's `.jl` files. We could restrict access only to a `res` or `assets`(Escher convention) folder inside the package so that `pkg/X/y.css` accesses `X/assets/y.css` for example.

The code in this patch is based on https://github.com/shashi/Escher.jl/pull/74 by @mdcfrancis

### CODE REVIEW

**Comment by shashi** [comment]
Another (more general) option here is to let other packages add their own middleware to the middleware stack Blink uses. I'll give that a go. Let me know what you think.

**Comment by rohitvarkey** [comment]
This would be a convenient way for other packages to register and serve static content they require in Blink. For example, to get ThreeJS to work with Blink, I had to [manually](https://gist.github.com/rohitvarkey/b3cfd79c9cd46414acac#file-threejsassets-jl) register all the static files with Blink. Having just one function that would do this for me would be nice to have!

> We could restrict access only to a res or assets(Escher convention) folder inside the package so that pkg/X/y.css accesses X/assets/y.css for example.

Sticking to the same convention across packages will help developers of packages that depend on these. Otherwise, if an Escher app is used in a Blink window, `pkg/X/y.css` will need to be made `pkg/X/assets/y.css` to be correctly found.

**Comment by shashi** [comment]
I've redone the PR to allow insertion of one arbitrary middleware instead.

However I can't get this to work:
```julia
using Blink


pkgroute =
  branch(req -> Mux.validpath(Pkg.dir(req[:params][:pkg]), joinpath(req[:path]...)),
         req -> Mux.fresp(joinpath(Pkg.dir(req[:params][:pkg]), req[:path]...)))

Blink.set_user_middleware!(Mux.route("/pkg/:pkg", Blink.pkgroute))
```

The error I get is

```
wrong number of arguments
 in anonymous at /home/shashi/.julia/v0.4/Mux/src/Mux.jl:15 (repeats 2 times)
 in anonymous at /home/shashi/.julia/v0.4/Blink/src/content/server.jl:69
 in anonymous at /home/shashi/.julia/v0.4/Mux/src/Mux.jl:8
 in anonymous at /home/shashi/.julia/v0.4/Mux/src/Mux.jl:15
 in anonymous at /home/shashi/.julia/v0.4/Mux/src/Mux.jl:8
 in toresponse at /home/shashi/.julia/v0.4/Mux/src/basics.jl:47
```

I think what I'm doing wrong should be obvious to @MikeInnes. Comments on better implementation / names / the idea are welcome!

**Comment by MikeInnes** [comment]
So we discussed this already, but Shashi figured out the issue above – the `route` call needed an endpoint (like `Mux.notfound()`) to finish off the `pkgroute` middleware.

As far as design is concerned – Blink already allows you to have your own arbitrary middleware by creating your own custom server :) Granted that's not hugely convenient, and there's the issue of composability between Blink dependents. I'm not sure this PR in its current form solves the latter issue though, because any two packages that use this functionality are going to clash.

I'm sure there's a way around that, but I think it might be easier just to make this a canonical Blink feature. Serving `$pkg/assets` seems like a good idea, but what could also work is to extend `Blink.resource` to accept a folder and serve all files under it. I think we need some kind of namespacing there, though.

**Comment by shashi** [comment]
@MikeInnes thanks for reviewing.

> As far as design is concerned – Blink already allows you to have your own arbitrary middleware by creating your own custom server :)

Could you describe how?

I'd be happy if to make this PR solve the latter issue well.

> I'm sure there's a way around that
Yeah I was thinking `set_middleware` could take a function which takes the currently set middleware and mux it if it wants. Still wonky because then you have ordering issues.

I think adding folders to `Blink.resource` works for me. However, the contract in Escher is that package authors using Escher do not need to register stuff / depend on Blink. `$pkg/assets` seems like the best solution.

> I think we need some kind of namespacing there, though.
what do you mean?

**Comment by MikeInnes** [comment]
No problem. Blink exposes its core functionality as a piece of middleware, and just sets up the simplest possible server containing that middleware. So you can just set up your own server containing `Blink.pagehandler`. (Although I'm not sure how that interacts with local usage, we probably need a way to have a way to configure the URL there.)

I think it should be doable, on the Escher side, as simply as `@require Blink Blink.resource(Pkg.dir("Escher", "assets"))`. The namespacing issue is how those are actually served, e.g. you could do `localhost/assets/foo.png` but then you have an issue when another package registers an "assets" folder. But that's potentially as simple as providing a namespace to the `resource` function.

Serving assets for for packages dependent on Escher is another issue. I'm not against the `$pkg/assets` approach at all, but having packages explicitly register their asset folders with Escher might be a good idea – it would solve this issue and potentially be good for other backends that you're not able to patch so easily :)

**Pull request closed without merging**
